-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer_behaviour.customer_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than average purchase amount?
WITH avg_purchase AS (
    SELECT AVG(purchase_amount) AS average_amount
    FROM customer_behaviour.customer_data
)
SELECT customer_id, purchase_amount, discount_applied
FROM customer_behaviour.customer_data, avg_purchase
WHERE discount_applied = 'Yes' AND purchase_amount > average_amount;

-- Q3. Which are the top 5 products with the highest average review ratings?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_rating
FROM customer_behaviour.customer_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amount between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer_behaviour.customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more on average than non-subscribed customers?
SELECT subscription_status, ROUND(AVG(purchase_amount),2) AS avg_spent, ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behaviour.customer_data
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
WITH discount_stats AS (
    SELECT item_purchased,
           COUNT(*) AS total_purchases,
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_purchases
    FROM customer_behaviour.customer_data
    GROUP BY item_purchased
)
SELECT item_purchased,
       ROUND((discount_purchases * 100.0) / total_purchases, 2) AS discount_percentage
FROM discount_stats
ORDER BY discount_percentage DESC
LIMIT 5;
